/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projeto.de.ed;

import java.io.IOException;


import projeto.de.ed.exceptions.*;

/**
 * <h3>
 * <strong>Classe App</strong>
 * </h3>
 *
 * @author Adão Araújo
 * @author Tiago Oliveira
 */
public class App {
    public static void main(String[] args) throws ElementNotFoundException, EmptyCollectionException {
        Menu menu = new Menu();
        try {
            menu.mainMenu();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
